### ISSUE TITLE
More mouse button

### ISSUE THREAD

**Issue by xnuk** [Seelge/TrackballScroll#30] opened 2023-06-16 12:15 UTC
I'm using [Elecom EX-G Pro](https://www.elecom.co.jp/products/M-XPT1MRBK.html), and it has 8 buttons, including left/middle/right click. Instead of back/front buttons, I want to assign the function to another button.

**Comment by Seelge** [comment] 2023-06-24 19:52
Thank you for the request, the trackball looks awesome. Remapping buttons to other functionality than scrolling is already covered by other software, I therefore consider it out of scope of TrackballScroll. I recommend [autohotkey](https://github.com/AutoHotkey/AutoHotkey) for this, remapping only requires a 1-line configuration.

**Closed as not planned by Seelge** 2023-06-24 19:52 UTC
Labels: duplicate, enhancement

**Comment by xnuk** [comment] 2023-06-24 23:57
> Remapping buttons to other functionality than scrolling

No, I want to assign scrolling to another mouse button, like 5th X-Button.

**Comment by Seelge** [comment] 2023-06-25 09:42
Thank you for the clarification, in that case, the issue is valid for TrackballScroll.

The Windows libraries support only 5 buttons (left, right, middle, x1, x2). I found a comment which suggests that additional mouse buttons actually send keyboard inputs.
Source: https://stackoverflow.com/q/27655619 (comment from Jan 5, 2015)

#28 already covers keyboard inputs and then should also cover the additional mouse buttons.
