### ISSUE TITLE
Some apps not responding to Scroll Event after Update to Version 2.1.1

### ISSUE THREAD

**Issue by leohinojosa** [Seelge/TrackballScroll#11] opened 2017-01-03 16:28 UTC
After upgrading to version 2.1.1, I have been having issues with my current setup.

Setup:
* Two {id 2,3 }monitors with 100% scaling, 1920 x 1080
* Laptop LCD {id:1 }with 125% scaling, , 1920 x 1080 
* Monitor Arrangement: 2   3   1

On this setup, i've noticed that for some reason some apps won't react to the scroll event, for example:
* Visual Studio 2015
* Outlook 2016
* Task Manager

Other Apps do work correctly ,such as
* Cmder
* Chrome
 
I'll try to debug a bit more and get more info on this issue

Thanks!

**Comment by Seelge** [comment] 2017-01-03 16:54
Thanks for your feedback.
* Is there a difference in behaviour if the program windows are located on the primary or the other monitors?
* Does it work after clicking to focus the scrollable area?

There also seems to be a difference between vertical and horizontal scroll events. Vertical scroll events seem to arrive at the window below the cursor and horizontal scroll events seem to arrive on the window having focus. E.g. if I focus the editor area in VS2015, both vertical and horizontal scrolling works while hovering above the editor area. If the solution explorer has focus, vertical scrolling works above the editor area but horizontal scrolling fails.

**Comment by Seelge** [comment] 2018-02-28 14:29
Reproduced using the task manager with two monitors using 100% scaling.

**Comment by mdelangeccc** [comment] 2018-11-29 23:41
Scroll is currently working for me in Outlook 2016, but does not work in Visual Studio 2017 editor.

**Comment by Seelge** [comment] 2018-12-01 01:56
Do other applications work, e.g. the file explorer?

**Comment by mdelangeccc** [comment] 2018-12-02 21:58
File Explorer works as expected and Chrome and Firefox browsers work also.

**Comment by pmalecka** [comment] 2018-12-04 15:40
Running as administrator remedies the issue for me..

**Comment by mdelangeccc** [comment] 2018-12-04 16:09
That remedies the issue for me as well, thank you @pmalecka

**Comment by Seelge** [comment] 2018-12-04 18:10
Running TrackballScroll as administrator should only be necessary for scrolling in other applications which are running in administrator mode, too.

**Comment by Seelge** [comment] 2021-03-27 20:32
I kept this bug open as I didn't test multiple monitors with different dpi scaling in the past. Now, with the same dpi scaling as in the description and Visual Studio 2019 and current Outlook from Office 365, scrolling works fine in both.

As the task manager and software running with elevated permissions seem to be guarded from the artificial scroll events, they are out of scope of TrackballScroll.

**Closed as completed by Seelge** 2021-03-27 20:32 UTC
Labels: bug
